//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEE.TinyBusinessMarket.BackEnd.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEE.TinyBusinessMarket.BackEnd.Localization.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik nie istnieje..
        /// </summary>
        public static string Download_FileNotExists {
            get {
                return ResourceManager.GetString("Download_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje zamówienie jest gotowe do pobrania.
        /// </summary>
        public static string MailSubject_DownloadToken {
            get {
                return ResourceManager.GetString("MailSubject_DownloadToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jednorazowe..
        /// </summary>
        public static string MailSubject_GeneratedToken {
            get {
                return ResourceManager.GetString("MailSubject_GeneratedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiadomienie o wystawieniu faktury VAT.
        /// </summary>
        public static string MailSubject_Invoice {
            get {
                return ResourceManager.GetString("MailSubject_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiadomienie o wystawieniu faktury pro forma.
        /// </summary>
        public static string MailSubject_ProForma {
            get {
                return ResourceManager.GetString("MailSubject_ProForma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient z takim adresem email nie istnieje w naszym Systemie..
        /// </summary>
        public static string Token_EmailNotExists {
            get {
                return ResourceManager.GetString("Token_EmailNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token jest nieaktywny..
        /// </summary>
        public static string Token_Inactive {
            get {
                return ResourceManager.GetString("Token_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwa nazwa użytkownika (login), bądź hasło..
        /// </summary>
        public static string Validation_BadLoginOrPassword {
            get {
                return ResourceManager.GetString("Validation_BadLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwy format adresu email..
        /// </summary>
        public static string Validation_EmailBadFormat {
            get {
                return ResourceManager.GetString("Validation_EmailBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient o takim adresie email już istnieje w naszym Systemie..
        /// </summary>
        public static string Validation_EmailExists {
            get {
                return ResourceManager.GetString("Validation_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwy numer NIP..
        /// </summary>
        public static string Validation_NipBadFormat {
            get {
                return ResourceManager.GetString("Validation_NipBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient o takim numerze NIP już istnieje w naszym Systemie..
        /// </summary>
        public static string Validation_NipExists {
            get {
                return ResourceManager.GetString("Validation_NipExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transakcja została już rozliczona..
        /// </summary>
        public static string Validation_OrderExpired {
            get {
                return ResourceManager.GetString("Validation_OrderExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwaga! W formularzu pojawiły się błędy. Popraw je i spróbuj zapisać formularz ponownie..
        /// </summary>
        public static string Validation_Summary_Error {
            get {
                return ResourceManager.GetString("Validation_Summary_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość wymagana..
        /// </summary>
        public static string Validation_ValueRequired {
            get {
                return ResourceManager.GetString("Validation_ValueRequired", resourceCulture);
            }
        }
    }
}
